# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'gui_pi.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(480, 320)
        
        # Set auto fill background
        MainWindow.setAutoFillBackground(True)
        
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.centralwidget.setAutoFillBackground(True)
        
        # Sidebar container - Modern website style
        self.verticalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(0, 0, 70, 290))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayoutWidget.setStyleSheet("""
            QWidget#verticalLayoutWidget {
                background: qlineargradient(x1:0, y1:0, x2:0, y2:1,
                    stop:0 #1b263b, stop:0.5 #0d1b2a, stop:1 #1b263b);
                border-right: 2px solid #00d4ff;
            }
        """)
        
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 5, 0, 5)
        self.verticalLayout.setSpacing(3)
        self.verticalLayout.setObjectName("verticalLayout")
        
        # Style for menu buttons - Modern Tab Style
        menuButtonStyle = """
            QPushButton {
                background-color: transparent;
                color: #778da9;
                border: none;
                border-radius: 8px;
                margin: 2px 5px;
                padding: 8px 5px;
                font-size: 9px;
                font-weight: bold;
                text-align: center;
            }
            QPushButton:hover {
                background-color: rgba(0, 212, 255, 0.15);
                color: #00d4ff;
            }
            QPushButton:pressed {
                background-color: rgba(0, 212, 255, 0.3);
            }
        """
        
        # Active button style - Glowing effect
        menuButtonActiveStyle = """
            QPushButton {
                background: qlineargradient(x1:0, y1:0, x2:0, y2:1,
                    stop:0 rgba(0, 212, 255, 0.4), stop:0.5 rgba(0, 212, 255, 0.2), stop:1 rgba(0, 212, 255, 0.4));
                color: #ffffff;
                border: 1px solid #00d4ff;
                border-radius: 8px;
                margin: 2px 5px;
                padding: 8px 5px;
                font-size: 9px;
                font-weight: bold;
                text-align: center;
            }
            QPushButton:hover {
                background: qlineargradient(x1:0, y1:0, x2:0, y2:1,
                    stop:0 rgba(0, 212, 255, 0.5), stop:0.5 rgba(0, 212, 255, 0.3), stop:1 rgba(0, 212, 255, 0.5));
            }
        """
        
        self.pushButton_2 = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_2.setStyleSheet(menuButtonActiveStyle)  # Default active
        self.pushButton_2.setMinimumHeight(50)
        self.pushButton_2.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.verticalLayout.addWidget(self.pushButton_2)
        
        self.pushButton_3 = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.pushButton_3.setObjectName("pushButton_3")
        self.pushButton_3.setStyleSheet(menuButtonStyle)
        self.pushButton_3.setMinimumHeight(50)
        self.pushButton_3.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.verticalLayout.addWidget(self.pushButton_3)
        
        self.pushButton = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.pushButton.setObjectName("pushButton")
        self.pushButton.setStyleSheet(menuButtonStyle)
        self.pushButton.setMinimumHeight(50)
        self.pushButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.verticalLayout.addWidget(self.pushButton)
        
        self.pushButton_4 = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.pushButton_4.setObjectName("pushButton_4")
        self.pushButton_4.setStyleSheet(menuButtonStyle)
        self.pushButton_4.setMinimumHeight(50)
        self.pushButton_4.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.verticalLayout.addWidget(self.pushButton_4)
        
        # Store styles for later use
        self.menuButtonStyle = menuButtonStyle
        self.menuButtonActiveStyle = menuButtonActiveStyle
        
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.stackedWidget = QtWidgets.QStackedWidget(self.centralwidget)
        self.stackedWidget.setGeometry(QtCore.QRect(70, 0, 410, 290))
        self.stackedWidget.setObjectName("stackedWidget")
        self.HOME = QtWidgets.QWidget()
        self.HOME.setObjectName("HOME")
        self.HOME.setAutoFillBackground(True)
        
        # Title - ĐỒ ÁN TỐT NGHIỆP with glow effect
        self.label = QtWidgets.QLabel(self.HOME)
        self.label.setGeometry(QtCore.QRect(10, 8, 390, 32))
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(True)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setStyleSheet("color: #ffffff; font-weight: bold; text-shadow: 0 0 10px #00d4ff;")
        self.label.setObjectName("label")
        
        # Top decorative line
        self.homeLineTop = QtWidgets.QFrame(self.HOME)
        self.homeLineTop.setGeometry(QtCore.QRect(80, 42, 250, 2))
        self.homeLineTop.setStyleSheet("background: qlineargradient(x1:0, y1:0, x2:1, y2:0, stop:0 transparent, stop:0.5 #00d4ff, stop:1 transparent);")
        self.homeLineTop.setFrameShape(QtWidgets.QFrame.HLine)
        
        # Logo HCMUTE
        self.label_2 = QtWidgets.QLabel(self.HOME)
        self.label_2.setGeometry(QtCore.QRect(175, 48, 60, 60))
        self.label_2.setText("")
        self.label_2.setPixmap(QtGui.QPixmap(":/images/logo_hcmute.png"))
        self.label_2.setScaledContents(True)
        self.label_2.setObjectName("label_2")
        
        # Subtitle - HỆ THỐNG QUẢN LÝ ĐIỆN NĂNG
        self.label_7 = QtWidgets.QLabel(self.HOME)
        self.label_7.setGeometry(QtCore.QRect(10, 112, 390, 26))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        self.label_7.setFont(font)
        self.label_7.setAlignment(QtCore.Qt.AlignCenter)
        self.label_7.setStyleSheet("color: #00d4ff; font-weight: bold;")
        self.label_7.setObjectName("label_7")
        
        # SVTH Section with card style
        self.svthCard = QtWidgets.QFrame(self.HOME)
        self.svthCard.setGeometry(QtCore.QRect(15, 145, 380, 55))
        self.svthCard.setStyleSheet("""
            background: qlineargradient(x1:0, y1:0, x2:1, y2:0, 
                stop:0 rgba(27, 38, 59, 0.8), stop:0.5 rgba(13, 27, 42, 0.9), stop:1 rgba(27, 38, 59, 0.8));
            border-radius: 8px;
            border: 1px solid #415a77;
        """)
        
        # SVTH Label
        self.label_6 = QtWidgets.QLabel(self.svthCard)
        self.label_6.setGeometry(QtCore.QRect(0, 5, 380, 18))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        self.label_6.setFont(font)
        self.label_6.setAlignment(QtCore.Qt.AlignCenter)
        self.label_6.setStyleSheet("color: #778da9; background: transparent; border: none;")
        self.label_6.setObjectName("label_6")
        
        # Student name 1
        self.label_4 = QtWidgets.QLabel(self.svthCard)
        self.label_4.setGeometry(QtCore.QRect(15, 26, 170, 22))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        self.label_4.setFont(font)
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setStyleSheet("color: #e0e1dd; background-color: rgba(0, 212, 255, 0.15); border-radius: 5px; border: none;")
        self.label_4.setObjectName("label_4")
        
        # Student name 2
        self.label_3 = QtWidgets.QLabel(self.svthCard)
        self.label_3.setGeometry(QtCore.QRect(195, 26, 170, 22))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        self.label_3.setFont(font)
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setStyleSheet("color: #e0e1dd; background-color: rgba(0, 212, 255, 0.15); border-radius: 5px; border: none;")
        self.label_3.setObjectName("label_3")
        
        # GVHD Section
        self.gvhdCard = QtWidgets.QFrame(self.HOME)
        self.gvhdCard.setGeometry(QtCore.QRect(80, 208, 250, 35))
        self.gvhdCard.setStyleSheet("""
            background: qlineargradient(x1:0, y1:0, x2:1, y2:0,
                stop:0 transparent, stop:0.2 rgba(243, 156, 18, 0.2), stop:0.8 rgba(243, 156, 18, 0.2), stop:1 transparent);
            border-radius: 6px;
            border: 1px solid #f39c12;
        """)
        
        # GVHD Label
        self.label_5 = QtWidgets.QLabel(self.gvhdCard)
        self.label_5.setGeometry(QtCore.QRect(0, 0, 250, 35))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        self.label_5.setFont(font)
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setStyleSheet("color: #f39c12; font-weight: bold; background: transparent; border: none;")
        self.label_5.setObjectName("label_5")
        
        # Year label
        self.yearLabel = QtWidgets.QLabel(self.HOME)
        self.yearLabel.setGeometry(QtCore.QRect(10, 250, 390, 18))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.yearLabel.setFont(font)
        self.yearLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.yearLabel.setStyleSheet("color: #778da9;")
        self.yearLabel.setText("Năm học: 2024 - 2025")
        self.yearLabel.setObjectName("yearLabel")
        
        # Exit button - modern style
        self.exit = QtWidgets.QPushButton(self.HOME)
        self.exit.setGeometry(QtCore.QRect(380, 5, 22, 22))
        self.exit.setStyleSheet("""
            QPushButton {
                background-color: #e74c3c;
                color: white;
                border-radius: 11px;
                font-weight: bold;
                font-size: 10px;
            }
            QPushButton:hover {
                background-color: #c0392b;
            }
        """)
        self.exit.setObjectName("exit")
        self.stackedWidget.addWidget(self.HOME)
        self.CONTROL = QtWidgets.QWidget()
        self.CONTROL.setObjectName("CONTROL")
        self.CONTROL.setAutoFillBackground(True)
        
        # Title: CONTROL DEVICES
        self.name_ctl = QtWidgets.QLabel(self.CONTROL)
        self.name_ctl.setGeometry(QtCore.QRect(10, 5, 385, 28))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.name_ctl.setFont(font)
        self.name_ctl.setAlignment(QtCore.Qt.AlignCenter)
        self.name_ctl.setStyleSheet("color: #00d4ff; font-weight: bold;")
        self.name_ctl.setObjectName("name_ctl")
        
        # Room indicator card
        self.roomCard = QtWidgets.QFrame(self.CONTROL)
        self.roomCard.setGeometry(QtCore.QRect(120, 35, 165, 35))
        self.roomCard.setStyleSheet("""
            background: qlineargradient(x1:0, y1:0, x2:1, y2:0,
                stop:0 transparent, stop:0.15 rgba(0, 212, 255, 0.2), stop:0.85 rgba(0, 212, 255, 0.2), stop:1 transparent);
            border-radius: 8px;
            border: 1px solid #1b4965;
        """)
        
        self.name_ctl_2 = QtWidgets.QLabel(self.roomCard)
        self.name_ctl_2.setGeometry(QtCore.QRect(10, 5, 60, 25))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.name_ctl_2.setFont(font)
        self.name_ctl_2.setStyleSheet("color: #778da9; background: transparent; border: none;")
        self.name_ctl_2.setObjectName("name_ctl_2")
        
        self.name_ctl_3 = QtWidgets.QLabel(self.roomCard)
        self.name_ctl_3.setGeometry(QtCore.QRect(75, 5, 80, 25))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.name_ctl_3.setFont(font)
        self.name_ctl_3.setStyleSheet("color: #00d4ff; background: transparent; border: none;")
        self.name_ctl_3.setObjectName("name_ctl_3")
        
        # Navigation buttons (left & right of room card)
        navButtonStyle = """
            QPushButton {
                background-color: #1b4965;
                color: #00d4ff;
                border: 1px solid #00d4ff;
                border-radius: 6px;
                font-weight: bold;
                font-size: 11px;
                outline: none;
            }
            QPushButton:hover {
                background-color: #00d4ff;
                color: #0d1b2a;
            }
            QPushButton:pressed {
                background-color: #0099cc;
                color: #ffffff;
            }
            QPushButton:focus {
                outline: none;
                border: 1px solid #00d4ff;
            }
        """
        
        self.pushButton_7 = QtWidgets.QPushButton(self.CONTROL)
        self.pushButton_7.setGeometry(QtCore.QRect(65, 40, 50, 28))
        self.pushButton_7.setStyleSheet(navButtonStyle)
        self.pushButton_7.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_7.setFocusPolicy(QtCore.Qt.NoFocus)
        self.pushButton_7.setObjectName("pushButton_7")
        
        self.pushButton_8 = QtWidgets.QPushButton(self.CONTROL)
        self.pushButton_8.setGeometry(QtCore.QRect(290, 40, 50, 28))
        self.pushButton_8.setStyleSheet(navButtonStyle)
        self.pushButton_8.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_8.setFocusPolicy(QtCore.Qt.NoFocus)
        self.pushButton_8.setObjectName("pushButton_8")
        
        # Device 1 Card
        self.device1Card = QtWidgets.QFrame(self.CONTROL)
        self.device1Card.setGeometry(QtCore.QRect(15, 80, 180, 90))
        self.device1Card.setStyleSheet("""
            QFrame {
                background: qlineargradient(x1:0, y1:0, x2:0, y2:1,
                    stop:0 #1b263b, stop:1 #0d1b2a);
                border-radius: 10px;
                border: 1px solid #415a77;
            }
        """)
        
        self.label_8 = QtWidgets.QLabel(self.device1Card)
        self.label_8.setGeometry(QtCore.QRect(15, 15, 150, 30))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        self.label_8.setFont(font)
        self.label_8.setStyleSheet("color: #e0e1dd; background: transparent; border: none;")
        self.label_8.setObjectName("label_8")
        
        # Toggle button style for devices
        toggleOnStyle = """
            QPushButton {
                background-color: #2ecc71;
                color: #ffffff;
                border: none;
                border-radius: 15px;
                font-weight: bold;
                font-size: 12px;
                outline: none;
            }
            QPushButton:hover {
                background-color: #27ae60;
            }
            QPushButton:pressed {
                background-color: #1e8449;
            }
            QPushButton:focus {
                outline: none;
                border: none;
            }
        """
        
        self.pushButton_5 = QtWidgets.QPushButton(self.device1Card)
        self.pushButton_5.setGeometry(QtCore.QRect(15, 50, 100, 32))
        self.pushButton_5.setStyleSheet(toggleOnStyle)
        self.pushButton_5.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_5.setFocusPolicy(QtCore.Qt.NoFocus)
        self.pushButton_5.setObjectName("pushButton_5")
        
        # Device 1 status indicator
        self.device1Status = QtWidgets.QLabel(self.device1Card)
        self.device1Status.setGeometry(QtCore.QRect(120, 52, 50, 28))
        self.device1Status.setText("ON")
        self.device1Status.setStyleSheet("color: #2ecc71; font-size: 12px; font-weight: bold; background: transparent; border: none;")
        self.device1Status.setAlignment(QtCore.Qt.AlignCenter)
        
        # Device 2 Card
        self.device2Card = QtWidgets.QFrame(self.CONTROL)
        self.device2Card.setGeometry(QtCore.QRect(205, 80, 180, 90))
        self.device2Card.setStyleSheet("""
            QFrame {
                background: qlineargradient(x1:0, y1:0, x2:0, y2:1,
                    stop:0 #1b263b, stop:1 #0d1b2a);
                border-radius: 10px;
                border: 1px solid #415a77;
            }
        """)
        
        self.label_9 = QtWidgets.QLabel(self.device2Card)
        self.label_9.setGeometry(QtCore.QRect(15, 15, 150, 30))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        self.label_9.setFont(font)
        self.label_9.setStyleSheet("color: #e0e1dd; background: transparent; border: none;")
        self.label_9.setObjectName("label_9")
        
        self.pushButton_6 = QtWidgets.QPushButton(self.device2Card)
        self.pushButton_6.setGeometry(QtCore.QRect(15, 50, 100, 32))
        self.pushButton_6.setStyleSheet(toggleOnStyle)
        self.pushButton_6.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_6.setFocusPolicy(QtCore.Qt.NoFocus)
        self.pushButton_6.setObjectName("pushButton_6")
        
        # Device 2 status indicator
        self.device2Status = QtWidgets.QLabel(self.device2Card)
        self.device2Status.setGeometry(QtCore.QRect(120, 52, 50, 28))
        self.device2Status.setText("ON")
        self.device2Status.setStyleSheet("color: #2ecc71; font-size: 12px; font-weight: bold; background: transparent; border: none;")
        self.device2Status.setAlignment(QtCore.Qt.AlignCenter)
        
        # Power info section
        self.powerInfoCard = QtWidgets.QFrame(self.CONTROL)
        self.powerInfoCard.setGeometry(QtCore.QRect(15, 180, 370, 75))
        self.powerInfoCard.setStyleSheet("""
            QFrame {
                background: qlineargradient(x1:0, y1:0, x2:1, y2:0,
                    stop:0 rgba(27, 38, 59, 0.9), stop:0.5 rgba(13, 27, 42, 0.95), stop:1 rgba(27, 38, 59, 0.9));
                border-radius: 10px;
                border: 1px solid #415a77;
            }
        """)
        
        self.powerLabel = QtWidgets.QLabel(self.powerInfoCard)
        self.powerLabel.setGeometry(QtCore.QRect(10, 10, 170, 25))
        self.powerLabel.setText("Công suất phòng:")
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        self.powerLabel.setFont(font)
        self.powerLabel.setStyleSheet("color: #778da9; background: transparent; border: none;")
        
        self.roomPowerValue = QtWidgets.QLabel(self.powerInfoCard)
        self.roomPowerValue.setGeometry(QtCore.QRect(180, 5, 180, 35))
        self.roomPowerValue.setText("0 W")
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        self.roomPowerValue.setFont(font)
        self.roomPowerValue.setStyleSheet("color: #00d4ff; background: transparent; border: none;")
        self.roomPowerValue.setAlignment(QtCore.Qt.AlignLeft | QtCore.Qt.AlignVCenter)
        
        self.energyLabel = QtWidgets.QLabel(self.powerInfoCard)
        self.energyLabel.setGeometry(QtCore.QRect(10, 45, 170, 22))
        self.energyLabel.setText("Điện năng tiêu thụ:")
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        self.energyLabel.setFont(font)
        self.energyLabel.setStyleSheet("color: #778da9; background: transparent; border: none;")
        
        self.roomEnergyValue = QtWidgets.QLabel(self.powerInfoCard)
        self.roomEnergyValue.setGeometry(QtCore.QRect(180, 42, 180, 28))
        self.roomEnergyValue.setText("0.00 kWh")
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        self.roomEnergyValue.setFont(font)
        self.roomEnergyValue.setStyleSheet("color: #f39c12; background: transparent; border: none;")
        self.roomEnergyValue.setAlignment(QtCore.Qt.AlignLeft | QtCore.Qt.AlignVCenter)
        
        self.stackedWidget.addWidget(self.CONTROL)
        self.REPORT = QtWidgets.QWidget()
        self.REPORT.setObjectName("REPORT")
        self.REPORT.setAutoFillBackground(True)
        self.TITLERP = QtWidgets.QLabel(self.REPORT)
        self.TITLERP.setGeometry(QtCore.QRect(5, 2, 60, 18))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.TITLERP.setFont(font)
        self.TITLERP.setAlignment(QtCore.Qt.AlignLeft)
        self.TITLERP.setStyleSheet("color: #00d4ff; font-weight: bold;")
        self.TITLERP.setObjectName("TITLERP")
        
        # Warning Label (top right)
        self.warningLabel = QtWidgets.QLabel(self.REPORT)
        self.warningLabel.setGeometry(QtCore.QRect(210, 2, 195, 18))
        self.warningLabel.setStyleSheet("color: #2ecc71; font-size: 9px; font-weight: bold;")
        self.warningLabel.setAlignment(QtCore.Qt.AlignRight)
        self.warningLabel.setText("")
        self.warningLabel.setObjectName("warningLabel")
        
        # Power Chart Area (left - full height)
        self.chartWidget = QtWidgets.QWidget(self.REPORT)
        self.chartWidget.setGeometry(QtCore.QRect(5, 22, 200, 245))
        self.chartWidget.setObjectName("chartWidget")
        self.chartWidget.setStyleSheet("background-color: #0d1b2a; border-radius: 6px; border: 1px solid #415a77;")
        
        # Chart Title placeholder (drawn by PowerChart)
        self.chartTitle = QtWidgets.QLabel(self.REPORT)
        self.chartTitle.setGeometry(QtCore.QRect(5, 22, 200, 16))
        self.chartTitle.setText("")
        self.chartTitle.setStyleSheet("background: transparent;")
        
        # Total Power Label (below chart)
        self.totalPowerLabel = QtWidgets.QLabel(self.REPORT)
        self.totalPowerLabel.setGeometry(QtCore.QRect(5, 250, 200, 20))
        self.totalPowerLabel.setStyleSheet("color: #00d4ff; font-size: 10px; font-weight: bold; background: transparent;")
        self.totalPowerLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.totalPowerLabel.setText("Tổng: 0 W")
        
        # Pie Chart Area (right top)
        self.pieWidget = QtWidgets.QWidget(self.REPORT)
        self.pieWidget.setGeometry(QtCore.QRect(210, 22, 195, 130))
        self.pieWidget.setObjectName("pieWidget")
        self.pieWidget.setStyleSheet("background-color: #0d1b2a; border-radius: 6px; border: 1px solid #415a77;")
        
        # Table (right bottom - below pie chart)
        self.REPORTTB = QtWidgets.QTableWidget(self.REPORT)
        self.REPORTTB.setGeometry(QtCore.QRect(210, 157, 195, 113))
        self.REPORTTB.setObjectName("REPORTTB")
        self.REPORTTB.setColumnCount(0)
        self.REPORTTB.setRowCount(0)
        
        self.stackedWidget.addWidget(self.REPORT)
        self.page = QtWidgets.QWidget()
        self.page.setObjectName("page")
        self.page.setAutoFillBackground(True)
        
        # Title
        self.name_ctl_4 = QtWidgets.QLabel(self.page)
        self.name_ctl_4.setGeometry(QtCore.QRect(10, 3, 390, 24))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        self.name_ctl_4.setFont(font)
        self.name_ctl_4.setAlignment(QtCore.Qt.AlignCenter)
        self.name_ctl_4.setStyleSheet("color: #00d4ff; font-weight: bold;")
        self.name_ctl_4.setObjectName("name_ctl_4")
        
        # ===== LEFT SIDE: Electricity Tier Prices =====
        self.tierTitle = QtWidgets.QLabel(self.page)
        self.tierTitle.setGeometry(QtCore.QRect(10, 28, 195, 20))
        self.tierTitle.setText("BIỂU GIÁ ĐIỆN (VNĐ/kWh)")
        self.tierTitle.setStyleSheet("color: #2ecc71; font-size: 10px; font-weight: bold;")
        self.tierTitle.setAlignment(QtCore.Qt.AlignCenter)
        
        # Tier inputs container
        self.tierInputs = []
        tier_labels = ["Bậc 1 (0-50):", "Bậc 2 (51-100):", "Bậc 3 (101-200):", 
                       "Bậc 4 (201-300):", "Bậc 5 (301-400):", "Bậc 6 (>400):"]
        tier_defaults = [1893, 1956, 2271, 2860, 3197, 3302]
        
        spinStyle = """
            QSpinBox {
                background-color: #1b263b;
                color: #2ecc71;
                border: 1px solid #2ecc71;
                border-radius: 4px;
                font-size: 10px;
                padding: 2px;
            }
            QSpinBox:hover {
                border: 1px solid #58d68d;
                background-color: #243447;
            }
            QSpinBox:focus {
                border: 2px solid #2ecc71;
            }
            QSpinBox::up-button, QSpinBox::down-button {
                width: 16px;
                background-color: #2ecc71;
                border-radius: 2px;
            }
            QSpinBox::up-button:hover, QSpinBox::down-button:hover {
                background-color: #58d68d;
            }
        """
        
        for i in range(6):
            y_pos = 48 + i * 28
            
            # Label
            lbl = QtWidgets.QLabel(self.page)
            lbl.setGeometry(QtCore.QRect(10, y_pos, 95, 24))
            lbl.setText(tier_labels[i])
            lbl.setStyleSheet("color: #778da9; font-size: 10px;")
            
            # SpinBox
            spin = QtWidgets.QSpinBox(self.page)
            spin.setGeometry(QtCore.QRect(105, y_pos, 80, 22))
            spin.setRange(500, 10000)
            spin.setValue(tier_defaults[i])
            spin.setStyleSheet(spinStyle)
            spin.setObjectName(f"tierInput_{i+1}")
            self.tierInputs.append(spin)
        
        # VAT input
        self.vatLabel = QtWidgets.QLabel(self.page)
        self.vatLabel.setGeometry(QtCore.QRect(10, 220, 95, 24))
        self.vatLabel.setText("VAT (%):")
        self.vatLabel.setStyleSheet("color: #778da9; font-size: 10px;")
        
        self.vatInput = QtWidgets.QSpinBox(self.page)
        self.vatInput.setGeometry(QtCore.QRect(105, 220, 80, 22))
        self.vatInput.setRange(0, 20)
        self.vatInput.setValue(8)
        self.vatInput.setSuffix("%")
        self.vatInput.setStyleSheet(spinStyle)
        self.vatInput.setObjectName("vatInput")
        
        # Save Tier button - Green style
        self.saveTierBtn = QtWidgets.QPushButton(self.page)
        self.saveTierBtn.setGeometry(QtCore.QRect(55, 248, 100, 28))
        self.saveTierBtn.setText("Lưu giá điện")
        self.saveTierBtn.setStyleSheet("""
            QPushButton {
                background-color: #2ecc71;
                color: white;
                border: none;
                border-radius: 6px;
                font-size: 10px;
                font-weight: bold;
                outline: none;
            }
            QPushButton:hover {
                background-color: #27ae60;
            }
            QPushButton:pressed {
                background-color: #1e8449;
            }
            QPushButton:focus {
                outline: none;
            }
        """)
        self.saveTierBtn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.saveTierBtn.setFocusPolicy(QtCore.Qt.NoFocus)
        self.saveTierBtn.setObjectName("saveTierBtn")
        
        # ===== RIGHT SIDE: Threshold Settings =====
        self.thresholdTitle = QtWidgets.QLabel(self.page)
        self.thresholdTitle.setGeometry(QtCore.QRect(210, 28, 195, 20))
        self.thresholdTitle.setText("CÀI ĐẶT NGƯỠNG (W)")
        self.thresholdTitle.setStyleSheet("color: #f39c12; font-size: 10px; font-weight: bold;")
        self.thresholdTitle.setAlignment(QtCore.Qt.AlignCenter)
        
        # Global thresholds
        self.globalThresholdLabel = QtWidgets.QLabel(self.page)
        self.globalThresholdLabel.setGeometry(QtCore.QRect(210, 48, 195, 18))
        self.globalThresholdLabel.setText("--- Ngưỡng chung ---")
        self.globalThresholdLabel.setStyleSheet("color: #778da9; font-size: 9px;")
        self.globalThresholdLabel.setAlignment(QtCore.Qt.AlignCenter)
        
        # Warning threshold
        self.warningThresholdLabel = QtWidgets.QLabel(self.page)
        self.warningThresholdLabel.setGeometry(QtCore.QRect(210, 68, 85, 22))
        self.warningThresholdLabel.setText("Cảnh báo:")
        self.warningThresholdLabel.setStyleSheet("color: #f39c12; font-size: 10px;")
        
        warningSpinStyle = """
            QSpinBox {
                background-color: #1b263b;
                color: #f39c12;
                border: 1px solid #f39c12;
                border-radius: 4px;
                font-size: 10px;
                padding: 2px;
            }
            QSpinBox:hover {
                border: 1px solid #f7b731;
                background-color: #243447;
            }
            QSpinBox::up-button, QSpinBox::down-button {
                width: 14px;
                background-color: #f39c12;
                border-radius: 2px;
            }
        """
        
        self.warningThresholdInput = QtWidgets.QSpinBox(self.page)
        self.warningThresholdInput.setGeometry(QtCore.QRect(300, 66, 75, 22))
        self.warningThresholdInput.setRange(100, 5000)
        self.warningThresholdInput.setValue(500)
        self.warningThresholdInput.setStyleSheet(warningSpinStyle)
        self.warningThresholdInput.setObjectName("warningThresholdInput")
        
        # Critical threshold
        self.criticalThresholdLabel = QtWidgets.QLabel(self.page)
        self.criticalThresholdLabel.setGeometry(QtCore.QRect(210, 92, 85, 22))
        self.criticalThresholdLabel.setText("Nguy hiểm:")
        self.criticalThresholdLabel.setStyleSheet("color: #e74c3c; font-size: 10px;")
        
        criticalSpinStyle = """
            QSpinBox {
                background-color: #1b263b;
                color: #e74c3c;
                border: 1px solid #e74c3c;
                border-radius: 4px;
                font-size: 10px;
                padding: 2px;
            }
            QSpinBox:hover {
                border: 1px solid #ec7063;
                background-color: #243447;
            }
            QSpinBox::up-button, QSpinBox::down-button {
                width: 14px;
                background-color: #e74c3c;
                border-radius: 2px;
            }
        """
        
        self.criticalThresholdInput = QtWidgets.QSpinBox(self.page)
        self.criticalThresholdInput.setGeometry(QtCore.QRect(300, 90, 75, 22))
        self.criticalThresholdInput.setRange(200, 10000)
        self.criticalThresholdInput.setValue(1000)
        self.criticalThresholdInput.setStyleSheet(criticalSpinStyle)
        self.criticalThresholdInput.setObjectName("criticalThresholdInput")
        
        # Room thresholds section
        self.roomThresholdLabel = QtWidgets.QLabel(self.page)
        self.roomThresholdLabel.setGeometry(QtCore.QRect(210, 118, 195, 18))
        self.roomThresholdLabel.setText("--- Ngưỡng theo phòng ---")
        self.roomThresholdLabel.setStyleSheet("color: #778da9; font-size: 9px;")
        self.roomThresholdLabel.setAlignment(QtCore.Qt.AlignCenter)
        
        # Room threshold inputs
        self.roomThresholdInputs = []
        room_names = ["Phòng 1:", "Phòng 2:", "Phòng 3:", "Phòng 4:"]
        
        roomSpinStyle = """
            QSpinBox {
                background-color: #1b263b;
                color: #00d4ff;
                border: 1px solid #00d4ff;
                border-radius: 4px;
                font-size: 10px;
                padding: 2px;
            }
            QSpinBox:hover {
                border: 1px solid #5dade2;
                background-color: #243447;
            }
            QSpinBox::up-button, QSpinBox::down-button {
                width: 14px;
                background-color: #00d4ff;
                border-radius: 2px;
            }
        """
        
        for i in range(4):
            y_pos = 138 + i * 26
            
            # Label
            lbl = QtWidgets.QLabel(self.page)
            lbl.setGeometry(QtCore.QRect(210, y_pos, 70, 22))
            lbl.setText(room_names[i])
            lbl.setStyleSheet("color: #00d4ff; font-size: 10px;")
            
            # SpinBox
            spin = QtWidgets.QSpinBox(self.page)
            spin.setGeometry(QtCore.QRect(280, y_pos, 75, 20))
            spin.setRange(50, 2000)
            spin.setValue(200)
            spin.setStyleSheet(roomSpinStyle)
            spin.setObjectName(f"roomThreshold_{i+1}")
            self.roomThresholdInputs.append(spin)
        
        # Save Threshold button - Orange style
        self.saveThresholdBtn = QtWidgets.QPushButton(self.page)
        self.saveThresholdBtn.setGeometry(QtCore.QRect(255, 248, 100, 28))
        self.saveThresholdBtn.setText("Lưu ngưỡng")
        self.saveThresholdBtn.setStyleSheet("""
            QPushButton {
                background-color: #f39c12;
                color: white;
                border: none;
                border-radius: 6px;
                font-size: 10px;
                font-weight: bold;
                outline: none;
            }
            QPushButton:hover {
                background-color: #d68910;
            }
            QPushButton:pressed {
                background-color: #b9770e;
            }
            QPushButton:focus {
                outline: none;
            }
        """)
        self.saveThresholdBtn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.saveThresholdBtn.setFocusPolicy(QtCore.Qt.NoFocus)
        self.saveThresholdBtn.setObjectName("saveThresholdBtn")
        
        # Decorative divider line
        self.setupDivider = QtWidgets.QFrame(self.page)
        self.setupDivider.setGeometry(QtCore.QRect(200, 35, 2, 235))
        self.setupDivider.setStyleSheet("background-color: #415a77;")
        self.setupDivider.setFrameShape(QtWidgets.QFrame.VLine)
        
        # Remove old tierLabel - we don't need it anymore
        self.tierLabel = QtWidgets.QLabel(self.page)
        self.tierLabel.setGeometry(QtCore.QRect(0, 0, 0, 0))
        self.tierLabel.setVisible(False)
        self.tierLabel.setObjectName("tierLabel")
        
        self.stackedWidget.addWidget(self.page)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 480, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.stackedWidget.setCurrentIndex(3)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pushButton_2.setText(_translate("MainWindow", "HOME"))
        self.pushButton_3.setText(_translate("MainWindow", "CONTROL"))
        self.pushButton.setText(_translate("MainWindow", "REPORT"))
        self.pushButton_4.setText(_translate("MainWindow", "SETUP"))
        self.label.setText(_translate("MainWindow", "ĐỒ ÁN TỐT NGHIỆP"))
        self.label_7.setText(_translate("MainWindow", "HỆ THỐNG QUẢN LÝ ĐIỆN NĂNG"))
        self.label_6.setText(_translate("MainWindow", "SVTH:"))
        self.label_4.setText(_translate("MainWindow", "NGUYỄN CHÍ PHÚC"))
        self.label_3.setText(_translate("MainWindow", "NGUYỄN LÊ PHÚC KHƯƠNG"))
        self.label_5.setText(_translate("MainWindow", "GVHD: Th.S VÕ ĐỨC DŨNG"))
        self.exit.setText(_translate("MainWindow", "X"))
        self.name_ctl.setText(_translate("MainWindow", "CONTROL DEVICES"))
        self.pushButton_5.setText(_translate("MainWindow", "ON"))
        self.label_8.setText(_translate("MainWindow", "Device 1"))
        self.name_ctl_2.setText(_translate("MainWindow", "ROOM:"))
        self.name_ctl_3.setText(_translate("MainWindow", "1"))
        self.label_9.setText(_translate("MainWindow", "Device 2"))
        self.pushButton_6.setText(_translate("MainWindow", "ON"))
        self.pushButton_7.setText(_translate("MainWindow", "PREV"))
        self.pushButton_8.setText(_translate("MainWindow", "NEXT"))
        self.TITLERP.setText(_translate("MainWindow", "BÁO CÁO"))
        self.name_ctl_4.setText(_translate("MainWindow", "CÀI ĐẶT"))
        self.tierLabel.setText(_translate("MainWindow", 
            "BIỂU GIÁ ĐIỆN SINH HOẠT 2024:\n\n"
            "Bậc 1: 0-50 kWh      → 1,893 đ/kWh\n"
            "Bậc 2: 51-100 kWh    → 1,956 đ/kWh\n"
            "Bậc 3: 101-200 kWh   → 2,271 đ/kWh\n"
            "Bậc 4: 201-300 kWh   → 2,860 đ/kWh\n"
            "Bậc 5: 301-400 kWh   → 3,197 đ/kWh\n"
            "Bậc 6: >400 kWh      → 3,302 đ/kWh\n\n"
            "VAT: 8%"))
import images_rc
